version: "3.4"

services:
  zookeeper:
    container_name: zookeeper-cqrs-bank
    image: bitnami/zookeeper
    restart: always
    ports:
      - "2181:2181"
    networks:
      - bank-cqrs

    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: kafka-cqrs-bank
    image: bitnami/kafka
    ports:
      - "9092:9092"
    networks:
      - bank-cqrs
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

  mongo:
    image: mongo
    container_name: mongo-cqrs-bank
    restart: always
    ports:
      - 27017:27017
    networks:
      - bank-cqrs
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - "mongodb_data_container:/data/db"

  mongo-express:
    image: mongo-express
    container_name: mongo-express-cqrs-bank
    restart: always
    ports:
      - 2020:8081
    networks:
      - bank-cqrs
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo-cqrs-bank:27017/

  mysql:
    image: mysql:8.0
    container_name: mysql-cqrs-bank
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    networks:
      - bank-cqrs
    volumes:
      - "mysql:/var/lib/mysql"
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"

  adminer:
    image: adminer
    container_name: adminer-cqrs-bank
    restart: always
    ports:
      - 3030:8080
    networks:
      - bank-cqrs

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongodb_data_container:
    driver: local
  mysql:
    driver: local
   
networks:
  bank-cqrs:
    driver: bridge

